export enum USER_ROLES {
  ADMIN = 'ADMIN',
  CASUAL = 'CASUAL',
}

export enum ROOM_TYPES {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}

export enum MESSAGE_TYPES {
  TEXT = 'TEXT',
  VOICE = 'VOICE',
}

export enum MESSAGE_RECEIVER_TYPES {
  GLOBAL = 'GLOBAL',
  ROOM = 'ROOM',
  PRIVATE = 'PRIVATE',
}

export enum FRIENDSHIP_STATUSES {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  IGNORED = 'IGNORED',
}

export enum USER_ONLINE_STATUSES {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}

export enum USER_GAME_STATUSES {
  NOT_IN_GAME = 'NOT_IN_GAME',
  WAITING_GAME_STARTING = 'WAITING_GAME_STARTING',
  GAME_IN_PROGRESS = 'GAME_IN_PROGRESS',
}

export enum LOCALES {
  en = 'en',
  ru = 'ru',
}

export enum SOUNDS {
  SOUNDS_1 = 'SOUNDS_1',
  SOUNDS_2 = 'SOUNDS_2',
  SOUNDS_3 = 'SOUNDS_3',
  SOUNDS_4 = 'SOUNDS_4',
  SOUNDS_5 = 'SOUNDS_5',
}
